### ISSUE TITLE
GNOME 3.0 compatibility

### ISSUE THREAD

**Issue by alwx** [alexkay/xmonad-log-applet#1]
There is no libpanelapplet-2.0 in GNOME 3.

**Comment by zmanian** [comment]
I'm also running into gnome 3 compatibility issues.

I get this message from autogen.sh

configure.ac:18: error: possibly undefined macro: AM_GCONF_SOURCE_2
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

**Comment by alexkay** [comment]
@alwx, @zmanian, gnome3 support is in the plans.

**Comment by zmanian** [comment]
Any thoughts about libappindicator vs the new style dbus applets? I'll take a stab at gnome3 support in my spare time.

**Comment by alexkay** [comment]
@zmanian, as far as i understand, libappindicator is for systray buttons/menus and is Ubuntu-specific. I'd rather we go the standard GNOME route, but I don't see why we couldn't support both.

With that in mind, feel free to work on either or both of them :)

**Comment by alexkay** [comment]
Should be fixed in master, pass `--with-panel=gnome3` to `./autogen.sh` when compiling.

Please let me know if it works for you, if it does I will cut a new version/tarball.

**Comment by zmanian** [comment]
Hi Alex,

On oneiric, the install path needed to be /usr/share/gnome-panel/4.0/applets.

I still haven't been able to make the DBUS connection between xmonad and the log panel applet.

Dbus is telling me that org.xmonad.Log doesn't exist.

I'm actively looking into it today.

**Comment by alexkay** [comment]
For Ubuntu you should add `--prefix=/usr` to `./autogen.sh`

**Comment by zmanian** [comment]
I'm using this snippet to try to test the DBUS connection but it doesn't appear to be working.

I'm using dbus-core because I'm on the latest haskell platform where dbus isn't available.

``` haskell
import qualified DBus.Address as DBA
import qualified DBus.Client.Simple as DBC
import qualified DBus.Types as DBT
import qualified Data.Text as T
import XMonad
main :: IO ()
main = do
  dbus <- DBC.connectSession
  DBC.emit dbus path ifc mem [DBT.toVariant $ T.pack "Hello"]
  where
    path = DBT.objectPath_ $ T.pack "/org/xmonad/Log"
    ifc = DBT.interfaceName_ $ T.pack "org.xmonad.Log"
    mem = DBT.memberName_ $ T.pack "Update"
```

**Comment by alexkay** [comment]
I have three suggestions:
- Reboot :)
- Try DBus from hackage, it doesn't compile with GHC 7.x, but it's just a question of substituting `import Control.Exception` with `import Control.OldException` in Internal.hsc
- Try xmonad.hs from this repo, it also uses dbus-client: https://github.com/danc86/xmonad-log-applet/blob/master/xmonad.hs.example

**Comment by alexkay** [comment]
By the way, my xmonad.hs is [here](https://github.com/alexkay/dotfiles/blob/master/xmonad.hs), I tested it on FreeBSD with GNOME 2 and on Fedora 15 with GNOME 3.

**Comment by alexkay** [comment]
Just to follow up, the problem was fixed after adding `--prefix=/usr` to `./autogen.sh`. I added a line to the README mentioning this.

**Comment by alexkay** [comment]
Well, apparently wiring applet's and dbus service file's location to $PREFIX was wrong, I changed autoconf to do the right thing in 81e7415, specifying `--prefix=/usr` is no longer needed.
