### ISSUE TITLE
GNOME 3 doesn't seem to respect PANEL_APPLET_EXPAND_MAJOR

### ISSUE THREAD

**Issue by liujimj** [alexkay/xmonad-log-applet#13]
I managed to get the gnome 3 version of the log applet working, but unfortunately it always shows ellipses '...' because gnome-panel has decided to ignore PANEL_APPLET_EXPAND_MAJOR.

This is true even on a new, otherwise-empty horizontal panel. I'm running Ubuntu 12.04 and Gnome Classic (basically the stock XMonad installation from repository).

Is there a way to set a fixed width, so as to not depend on gnome-panel setting it properly? I've been fiddling with gnome-panel.css, but I don't believe it actually is able to set panel applet width.

**Comment by liujimj** [comment]
Below is a screenshot of the issue.

![Screenshot from 2012-12-31 20:10:24](https://f.cloud.github.com/assets/704823/37126/8c828de4-53c9-11e2-9d14-822c91de749b.png)

**Comment by alexkay** [comment]
GNOME 3 panel has 3 applet alignment modes, from the screen-shot it looks like your applet is right-aligned. Could you Alt-Right-Click and move it to the left of the panel?

**Comment by liujimj** [comment]
Ah, that seems to have worked. Sorry for the false alarm, and thanks for quick response.
