### ISSUE TITLE
xmonad-log-applet with unity-2d-panel

### ISSUE THREAD

**Issue by ghost** [alexkay/xmonad-log-applet#2]
Hi Alex,

You haven't happen to try to integrate xmonad-log-applet with the unity-2d-panel?

There are a couple of pages that give tips on how to integrate xmonad with unity-2d:

http://markhansen.co.nz/xmonad-ubuntu-oneiric/
http://www.haskell.org/haskellwiki/Xmonad/Using_xmonad_in_Unity_2D

But on neither there's info on how to get the xmonad-log-applet to show in that panel.

**Comment by alexkay** [comment]
I'll check how to implement this, thanks for opening the issue!

**Comment by jefallbright** [comment]
Since "upgrading" to Ubuntu 11.10 Oneiric I'm eagerly looking forward to a solution for x-l-a with Unity-2d.

**Comment by void** [comment]
The applet is only for gnome-panel, unity panel doesn't support them.

**Comment by alexkay** [comment]
@void, it's also for gnome3 and xfce panels. If anyone wants to tackle this issue -- feel free to do so. I don't use Ubuntu and don't have much time lately.

**Comment by hamaxx** [comment]
If anyone is still interested: https://github.com/hamaxx/unity-2d-for-xmonad

**Comment by alexkay** [comment]
Closing this since unity-2d has been discontinued in Ubuntu 14.04
