### ISSUE TITLE
Use dbus-core instead of DBus?

### ISSUE THREAD

**Issue by ghost** [alexkay/xmonad-log-applet#4]
any chance to get an example xmonad.hs using dbus-core instead of DBus? cause i can't compile DBus but, i already compiled and packges dbus-core?

**Comment by alexkay** [comment]
You could try using this xmonad.hs as an example: https://github.com/danc86/xmonad-log-applet/blob/master/xmonad.hs.example

If you manage to get it working, could you submit a pull request?

Another alternative is to compile DBus, I described the procedure in this blog post, it's actually very simple: http://versia.com/2011/09/xmonad-log-applet-gnome-xfce/

**Comment by ghost** [comment]
ty, i compiled de DBus w the blog post :D

**Comment by alexkay** [comment]
On 23 November 2011 00:47, cxs00
reply@reply.github.com
wrote:

> a question... is there any way to change the font for the applet? or i need to modify(or create) the pangoColor function(in xmonad.hs) to change the font?

The applet uses the default theme font, but you can indeed adjust it
with pango mark up:
http://developer.gnome.org/pango/stable/PangoMarkupFormat.html

Cheers,
Alex

**Comment by ghost** [comment]
ty, I deleted the post, cause like 1 min after writing the comment I realized how to do it :D

**Comment by alexkay** [comment]
Fixed by the pull request from issue 6.
