### ISSUE TITLE
Accents in XFCE panel

### ISSUE THREAD

**Issue by Chadehoc** [alexkay/xmonad-log-applet#5]
Using xmonad-log-applet with the XFCE panel, I had to patch it to show correctly accents.
The applet is fed with unicode strings but those have to be converted to iso-8859-1 to appear in the panel.

I suggest to include the following patch for XFCE:

diff --git a/main.c b/main.c
index a098885..e2cd6d6 100644
--- a/main.c
+++ b/main.c
@@ -22,7 +22,9 @@

 static void signal_handler(DBusGProxy *obj, const char *msg, GtkWidget *widget)
 {
-    gtk_label_set_markup(GTK_LABEL(widget), msg);
-    gchar\* iso = g_convert(msg, -1, "ISO-8859-1", "UTF-8", NULL, NULL, NULL);
-    gtk_label_set_markup(GTK_LABEL(widget), iso);
-    g_free(iso); 
  }
  
  static void set_up_dbus_transfer(GtkWidget *buf)

**Comment by alexkay** [comment]
I suspect it's caused by your locale. Could you run `locale`in the terminal and paste the output?

I tested Xfce with the en_US.UTF-8 locale, and accented Latin, Cyrillic, Chinese and Japanese characters all show up fine.

**Comment by Chadehoc** [comment]
My locale is fr_FR.utf8 for everything (save LC_ALL empty).
An xprop on the panel itself yields the same locale.

And GTK is supposed to use only utf8... That's strange, I really have to convert to iso-8859-1 to display correctly !

I will keep this patch for myself, since it seems more a problem in my personal config. Thanks.
